version: 2

sources:
  - name: policy_servicing
    schema: l1
    tables:
      - name: policy_servicing_policy_attributes
        description: "Initial l1 source data"
        columns:
          - name: certificate_id
            description: n/a
            tests:
              - not_null
          - name: mgic_loan_id
            description: n/a
          - name: policy_id
            description: n/a
          - name: policy_type
            description: n/a